version: '3'

services:  
  workflow-modeler:
    image: planqk/workflow-modeler:v1.3.1
    environment:
     CAMUNDA_ENDPOINT: http://${PUBLIC_HOSTNAME}:8090/engine-rest
     ENABLE_DATA_FLOW_PLUGIN: 'false'
     ENABLE_OPENTOSCA_PLUGIN: 'false'
     ENABLE_PLANQK_PLUGIN: 'false'
     ENABLE_QHANA_PLUGIN: 'false'
     ENABLE_QUANTME_PLUGIN: 'true'
     QRM_USERNAME: ${QRM_USERNAME}
     QRM_REPONAME: ${QRM_REPONAME}
     QRM_REPOPATH: ${QRM_REPOPATH}
     WINERY_ENDPOINT: http://${PUBLIC_HOSTNAME}:8093/winery
    ports:
      - 8080:8080
    networks:
      - use-case-3

  camunda-engine:
    build: camunda
    ports:
      - 8090:8080
    networks:
      - use-case-3

  oracle-service:
    build: oracle-service/.
    ports:
      - '8081:5000'
    networks:
      - use-case-3

  execution-service:
    build: ./execution-service
    ports:
      - '8082:5000'
    networks:
      - use-case-3

  provenance-service:
    build: ./provenance-service
    ports:
      - '8083:5000'
    networks:
      - use-case-3

networks:
  use-case-3:
    driver: bridge
