version: '3'

services:
  workflow-modeler:
    image: planqk/workflow-modeler:v1.3.2
    environment:
     CAMUNDA_ENDPOINT: http://${PUBLIC_HOSTNAME}:8090/engine-rest
     ENABLE_DATA_FLOW_PLUGIN: 'false'
     ENABLE_OPENTOSCA_PLUGIN: 'false'
     ENABLE_PLANQK_PLUGIN: 'false'
     ENABLE_QHANA_PLUGIN: 'false'
     ENABLE_QUANTME_PLUGIN: 'true'
     QRM_USERNAME: ${QRM_USERNAME}
     QRM_REPONAME: ${QRM_REPONAME}
     QRM_REPOPATH: ${QRM_REPOPATH}
     WINERY_ENDPOINT: http://${PUBLIC_HOSTNAME}:8093/winery
    ports:
      - 8080:8080
    networks:
      - use-case-4

  camunda-engine:
    build: camunda
    ports:
      - 8090:8080
    networks:
      - use-case-4

  winery:
    image: opentosca/winery:v3.0.8-M1
    logging:
      driver: none
    ports:
      - 8093:8080
    networks:
      - use-case-4
      
  execution-service:
    image: planqk/execution-service:v0.2.0
    ports:
      - '5075:5075'
    networks:
      - use-case-4
      
  optimization-service:
    image: planqk/optimization-service:v0.3.0
    ports:
      - '5074:5074'
    environment:
      CAMUNDA_ENDPOINT: http://${PUBLIC_HOSTNAME}:8090/engine-rest
    networks:
      - use-case-4
      
  objective-evaluation-service:
    image: planqk/objective-evaluation-service:v1.0.0
    ports:
      - '5072:5072'
    networks:
      - use-case-4
      
  circuit-generation-service:
    image: planqk/quantum-circuit-generator:v1.0.2
    ports:
      - '5073:5073'
    networks:
      - use-case-4  
      
  distance-matrix:
    image: planqk/distance-matrix-app:v1.0.0
    ports:
      - '5078:8101'
    networks:
      - use-case-4
      
  map-generation:
    image: planqk/map-generation-app:v1.0.0
    ports:
      - '5079:8102'
    networks:
      - use-case-4

  quokka-gateway:
    image: planqk/quokka-gateway:0.2.0
    ports:
      - '6474:6474'
    networks:
      - use-case-4

networks:
  use-case-4:
    driver: bridge
